steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy
  entrypoint: bash
  args: [ '-c', 'if [ "$BRANCH_NAME" == "develop" ]; then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/dags; else echo "Working on $BRANCH_NAME"; fi']
substitutions:
    _COMPOSER_BUCKET: us-central1-data-pipeline-c-fa0d0c3c-bucket
# options:
#   logging: CLOUD_LOGGING_ONLY
logsBucket: 'gs://mylogsbucket123'